# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:

- name: Resource_group
  type: string
  default: 'default value!'
   
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
   script: |
     az login --service-principal -u $(sp_app_id) -p $(sp_app_password) --tenant $(tenant_id)
- task: CmdLine@2
  inputs:
    script: az acr login --name $($1) 
- task: Bash@3
  inputs:
    filePath: 'hello.sh'
    arguments: '$($1) $($2)'
