# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:

- name: Resource_group
  type: string
  default: 'default value!'
   
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
   script: |
    az acr login --name ${{ parameters.Registry }} --username $(aad-username) --password $(aad-password)
- task: CmdLine@2
  inputs:
    script: az acr login --name ${{ parameters.Registry}} 
- task: Bash@3
  inputs:
    filePath: 'hello.sh'
    arguments: '${{ parameters.Registry}} ${{ parameters.Timestamp }}'
