# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:

- name: loginserver
  type: string
  default: 'default value!'
- name: docker_username
  type: string
  default: 'default value!'
- name: docker_password
  type: string
  default: 'default value!'  
- name: Resource_group
  type: string
  default: 'default value!'
- name: Registry
  type: string
  default: 'default value!'    
- name: Timestamp
  type: string
  default: 'default value!'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: docker login ${{loginserver}} --username ${{docker_username}} --password ${{docker_password}}   
- task: CmdLine@2
  inputs:
    script: az acr login --name ${{Registry}}    
- task: Bash@3
  inputs:
    filePath: 'hello.sh'
    arguments: '${{ parameters.Repository_Selection}} ${{ parameters.Timestamp }}'
