apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: image-deletion_inside_acr
  annotations:
    github.com/project-slug: Pree-byte/image-deletion_inside_acr
spec:
  type: other
  lifecycle: unknown
  owner: guests
